name: moodle-customer1
services:
  db:
    environment:
      POSTGRES_DB: moodle_customer1
      POSTGRES_PASSWORD: customer1password
      POSTGRES_USER: moodleuser1
    image: postgres
    networks:
      moodle-network: null
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/postgresql/data
        volume: {}
  moodle:
    environment:
      MOODLE_ADMIN: admin
      MOODLE_ADMIN_PASSWORD: customer1password
      MOODLE_DB_HOST: db
      MOODLE_DB_NAME: moodle_customer1
      MOODLE_DB_PASSWORD: customer1password
      MOODLE_DB_PORT: "5432"
      MOODLE_DB_TYPE: pgsql
      MOODLE_DB_USER: moodleuser1
      MOODLE_SSL: "true"
      MOODLE_URL: https://moodlecus1.mosalam.com
    image: ellakcy/moodle:postgresql_apache_403_php8.2
    labels:
      traefik.docker.network: traefik-public
      traefik.enable: "true"
      traefik.http.routers.moodle-customer1-http.entrypoints: http
      traefik.http.routers.moodle-customer1-http.middlewares: https-redirect
      traefik.http.routers.moodle-customer1-http.rule: Host(`moodlecus1.mosalam.com`)
      traefik.http.routers.moodle-customer1-http.service: moodle-customer1
      traefik.http.routers.moodle-customer1-https.entrypoints: https
      traefik.http.routers.moodle-customer1-https.rule: Host(`moodlecus1.mosalam.com`)
      traefik.http.routers.moodle-customer1-https.service: moodle-customer1
      traefik.http.routers.moodle-customer1-https.tls: "true"
      traefik.http.routers.moodle-customer1-https.tls.certresolver: le
      traefik.http.services.moodle-customer1.loadbalancer.server.port: "80"
    networks:
      moodle-network: null
      traefik-public: null
    volumes:
      - type: volume
        source: moodle_data
        target: /var/moodledata
        volume: {}
      - type: volume
        source: moodlesourcecode_data
        target: /var/www/html
        volume: {}
      - type: bind
        source: /root/gitops/moodle/moodleam-php-custom-ini/filesizeLimit.ini
        target: /usr/local/etc/php/conf.d/filesizeLimit.ini
        bind:
          create_host_path: true
networks:
  moodle-network:
    name: moodle_network_customer1
  traefik-public:
    name: traefik-public
    driver_opts:
      com.docker.network.driver.mtu: "1400"
    external: true
volumes:
  db_data:
    name: db_data_customer1
    driver: local
  moodle_data:
    name: moodle_data_customer1
    driver: local
  moodlesourcecode_data:
    name: moodlesourcecode_data_customer1
    driver: local
