networks:
  traefik-public:
    name: traefik-public
    external: true
    driver_opts:
      com.docker.network.driver.mtu: 1400

  moodle-network:
    name: ${MOODLE_NETWORK_NAME}
    external: false

services:
  db:
    image: postgres
    networks:
      - moodle-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  moodle:
    image: ellakcy/moodle:postgresql_apache_403_php8.2
    networks:
      - traefik-public
      - moodle-network
    environment:
      MOODLE_DB_HOST: db
      MOODLE_DB_NAME: ${MOODLE_DB_NAME}
      MOODLE_DB_USER: ${MOODLE_DB_USER}
      MOODLE_DB_PASSWORD: ${MOODLE_DB_PASSWORD}
      MOODLE_ADMIN: admin
      MOODLE_ADMIN_PASSWORD: ${MOODLE_ADMIN_PASSWORD}
      MOODLE_URL: https://${MOODLE_URL}
      MOODLE_DB_TYPE: pgsql
      MOODLE_DB_PORT: 5432
      MOODLE_SSL: true
    labels:
      - traefik.docker.network=traefik-public
      - traefik.enable=true
      - traefik.http.routers.${ROUTER}-http.entrypoints=http
      - traefik.http.routers.${ROUTER}-http.middlewares=https-redirect
      - traefik.http.routers.${ROUTER}-http.rule=Host(`${MOODLE_URL}`)
      - traefik.http.routers.${ROUTER}-http.service=${ROUTER}
      - traefik.http.routers.${ROUTER}-https.entrypoints=https
      - traefik.http.routers.${ROUTER}-https.rule=Host(`${MOODLE_URL}`)
      - traefik.http.routers.${ROUTER}-https.service=${ROUTER}
      - traefik.http.routers.${ROUTER}-https.tls=true
      - traefik.http.routers.${ROUTER}-https.tls.certresolver=le
      - traefik.http.services.${ROUTER}.loadbalancer.server.port=80
    volumes:
      - moodle_data:/var/moodledata
      - moodlesourcecode_data:/var/www/html
      - ./moodleam-php-custom-ini/filesizeLimit.ini:/usr/local/etc/php/conf.d/filesizeLimit.ini
volumes:
  db_data:
    name: ${DB_VOLUME_NAME}
    driver: local
  moodle_data:
    name: ${MOODLE_DATA_VOLUME_NAME}
    driver: local
  moodlesourcecode_data:
    name: ${MOODLE_SOURCE_VOLUME_NAME}
    driver: local

